name: Check Source Branch
on:
  pull_request:
    branches:
      - main
jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if source branch is 'develop'
        if: github.base_ref == 'main' && (github.head_ref != 'develop' || !startsWith(github.head_ref, 'hotfix/'))
        run: |
          echo "Error: Pull requests to 'main' must originate from 'develop' branch."
          exit 1